### ISSUE TITLE
Links vs Breadcrumbs

### ISSUE THREAD

**Issue by newbonedayatatime** [selfire1/BibleGateway-to-Obsidian#23]
I was wondering how I can get back the old way of moving from chapter to chapter by using links vs using the breadcrumbs plugin?

I am not a big fan of the breadcrumbs navigation and it seems like any option i choose to download the scripture are missing the links page navigation.  So when I download the bible without breadcrumb, I have no way of navigating from chapter to chapter. 

Can you help please help with this? 

The solution to just go back to the older versions would not be good for me because of other issues like: 1. Each chapter repeats chapter one from each book. 2. The books with numbers don't work well. So this newer version fixes these two issues for me but leaves out the old links navigation that I actually enjoy.

Thank you sooo much for all your hard work. This is such a gift. 

Thanks!

**Comment by nfantis** [comment]
@newbonedayatatime 

I just stumbled on this today and was having the same issue.  I think this is a bug in the latest script.  I'm not a coder, so I can't tell you why this works or the significance of the brackets, but this change works:

Change Line 188 in the `bg2obs.sh` file from:
```
if [[ ${breadcrumbs_yaml} -eq "true" ]]; then
```

to:
```
if ${breadcrumbs_yaml} -eq "true"; then
```

You should see the links show up along the top instead of just the three asterisks. 
```
# Genesis 1

[[Genesis]] | [[Gen 2|Genesis 2 →]]
***

# Genesis 1 (World English Bible)
```

Hope this helps!

**Comment by newbonedayatatime** [comment]
Thank you so much. It worked! Wow. the best! Thank you again.

**Comment by JS211** [comment]
I can also confirm that this fix works. Thank you.

**Comment by BTCarpenter** [comment]
Many thanks for the navigation fix!

**Comment by selfire1** [comment]
Fixed in https://github.com/selfire1/BibleGateway-to-Obsidian/pull/27.
